"""поменял типы salary_from и salary_to на int

Revision ID: bd79763e85bd
Revises: 728de05e6a3a
Create Date: 2023-01-11 14:07:19.514166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd79763e85bd'
down_revision = '728de05e6a3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'salary_from',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_comment='Зарплата от',
               existing_nullable=True,
               postgresql_using='salary_from::integer')
    op.alter_column('jobs', 'salary_to',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_comment='Зарплата до',
               existing_nullable=True,
               postgresql_using='salary_to::integer')
    # op.execute('ALTER TABLE jobs ALTER COLUMN salary_from TYPE integer USING salary_from::integer')
    # op.execute('ALTER TABLE jobs ALTER COLUMN salary_to TYPE integer USING salary_to::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'salary_to',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_comment='Зарплата до',
               existing_nullable=True,
               postgresql_using='salary_to::varchar(100)')
    op.alter_column('jobs', 'salary_from',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_comment='Зарплата от',
               existing_nullable=True,
               postgresql_using='salary_from::varchar(100)')
    # op.execute('ALTER TABLE jobs ALTER COLUMN salary_from TYPE varchar(100) USING salary_from::varchar')
    # op.execute('ALTER TABLE jobs ALTER COLUMN salary_to TYPE varchar(100) USING salary_to::varchar')
    # ### end Alembic commands ###
